### ISSUE TITLE
Where is "public.sepsis3" created?

### ISSUE THREAD

**Issue by sgfin** [spfohl/cs238_sepsis_rl#1]
Trying to rerun the mimic scripts, and was able to run the scripts of the form "*_all_rl.sql", but when I try to run "create_cohort_table.sql", I get the following error:

`DROP MATERIALIZED VIEW
psql:create_cohort_table.sql:34: ERROR:  relation "sepsis3" does not exist
LINE 19:     FROM sepsis3 as s3`

Searching through the repo, I can't see where sepsis3 is created. Is there another script where that happens, or am I just missing something?

**Comment by sgfin** [comment]
Nevermind looks like it's from here:

https://github.com/alistairewj/sepsis3-mimic

**Comment by paulrich1234** [comment]
hello   @sgfin,did you finally get the original data ? if so ,could you tell me how to get it ? thank you

**Comment by spfohl** [comment]
Hi @paulrich1234, you'll need to get MIMIC-III from Physionet, build the concept tables here https://github.com/MIT-LCP/mimic-code and then run make_tables.sql from here: https://github.com/alistairewj/sepsis3-mimic/tree/master/query

**Comment by paulrich1234** [comment]
hello @ @spfohl   Thank you for your timely reply  ,i think i have got the result as your instruction recently .Thank you
